abstract: Use Template::Declare with Catalyst
author: Jonathan Rockway, C<< <jrockway at cpan.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-View-Template-Declare
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::View: 0
  Module::Pluggable::Object: 0
  NEXT: 0
  Template::Declare: 0.21
version: 0.01
